<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Tools">
    <Actions category="tool-shortcuts">
        <Action name="switch_liquify">
        <icon></icon>
        <text>Liquify Tool</text>
        <whatsThis></whatsThis>
        <toolTip>Liquify Tool</toolTip>
        <iconText>Liquify Tool</iconText>
        <activationFlags>1</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>